### PR TITLE
add elephant image

### PR DESCRIPTION
**Pull request by kohct1**

### CODE REVIEW

**Comment by saumilthecode** [comment]
what is that file name 💀

**Comment by saumilthecode** [comment]
ill add it soon(real)

**Comment by kohct1** [comment]
THATS MY NAME YOU HATER

**Comment by kohct1** [comment]
hi im kairos

**Comment by kohct1** [comment]
hater!! cyberbullying!!

**Comment by saumilthecode** [comment]
oh mbad i thought you wrote someone else's name and named the commit message accordingly 💀

**Comment by Kairos-T** [comment]
cyberbullying!!!

**Comment by Kairos-T** [comment]
bbcs safe space WHEN

**Comment by saumilthecode** [comment]
misinformation 
12-121001_download-zip-archive-penguins-of-madagascar-model-hd

**Comment by saumilthecode** [comment]
merge now

**Pull request merged**
